models/Reservas.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "reservas".
 *
 * @property int $habitaciones_id
 * @property string $fecha_entrada
 * @property string $fecha_salida
 * @property int $clientes_id
 * @property string $precio
 * @property string $observacion
 *
 * @property Clientes $clientes
 * @property Habitaciones $habitaciones
 */
class Reservas extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'reservas';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['habitaciones, clientes, dias'], 'safe'],
            [['habitaciones_id', 'fecha_entrada', 'fecha_salida'], 'required'],
            [['habitaciones_id', 'clientes_id'], 'default', 'value' => null],
            [['habitaciones_id', 'clientes_id'], 'integer'],
            [['fecha_entrada', 'fecha_salida'], 'safe'],
            [['precio'], 'number'],
            [['observacion'], 'string'],
            [['habitaciones_id', 'fecha_entrada', 'fecha_salida'], 'unique', 'targetAttribute' => ['habitaciones_id', 'fecha_entrada', 'fecha_salida']],
            [['clientes_id'], 'exist', 'skipOnError' => true, 'targetClass' => Clientes::className(), 'targetAttribute' => ['clientes_id' => 'id']],
            [['habitaciones_id'], 'exist', 'skipOnError' => true, 'targetClass' => Habitaciones::className(), 'targetAttribute' => ['habitaciones_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'Reserva ID',
            'habitaciones' => 'Habitación',
            'clientes' => 'Clientes',
            'dias' => 'Días',
            'habitaciones_id' => 'Habitación ID',
            'clientes_id' => 'Cliente ID',
            'fecha_entrada' => 'Entrada',
            'fecha_salida' => 'Salida',
            'precio' => 'Precio',
            'observacion' => 'Observación',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getClientes()
    {
        return $this->hasOne(Clientes::className(), ['id' => 'clientes_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHabitaciones()
    {
        return $this->hasOne(Habitaciones::className(), ['id' => 'habitaciones_id']);
    }

    /**
     * Devuelve la cantidad de días que ha reservado.
     * @return mixed Integer
     */
    public function getDias()
    {
        $f1 = $this->fecha_entrada;
        $f2 = $this->fecha_salida;
        $dias = abs((strtotime($f1) - strtotime($f2))/86400);

        return $dias;
    }
}

controllers/ClientesController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Clientes;
use app\models\ClientesSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ClientesController implements the CRUD actions for Clientes model.
 */
class ClientesController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Clientes models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ClientesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Clientes model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Clientes model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Clientes();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Clientes model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Clientes model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Clientes model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Clientes the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Clientes::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/HabitacionesController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Habitaciones;
use app\models\HabitacionesSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * HabitacionesController implements the CRUD actions for Habitaciones model.
 */
class HabitacionesController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Habitaciones models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new HabitacionesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Habitaciones model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Habitaciones model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Habitaciones();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Habitaciones model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Habitaciones model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Habitaciones model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Habitaciones the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Habitaciones::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/ReservasController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Reservas;
use app\models\ReservasSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ReservasController implements the CRUD actions for Reservas model.
 */
class ReservasController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Reservas models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ReservasSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Reservas model.
     * @param integer $habitaciones_id
     * @param string $fecha_entrada
     * @param string $fecha_salida
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($habitaciones_id, $fecha_entrada, $fecha_salida)
    {
        return $this->render('view', [
            'model' => $this->findModel($habitaciones_id, $fecha_entrada, $fecha_salida),
        ]);
    }

    /**
     * Creates a new Reservas model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Reservas();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'habitaciones_id' => $model->habitaciones_id, 'fecha_entrada' => $model->fecha_entrada, 'fecha_salida' => $model->fecha_salida]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Reservas model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $habitaciones_id
     * @param string $fecha_entrada
     * @param string $fecha_salida
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($habitaciones_id, $fecha_entrada, $fecha_salida)
    {
        $model = $this->findModel($habitaciones_id, $fecha_entrada, $fecha_salida);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'habitaciones_id' => $model->habitaciones_id, 'fecha_entrada' => $model->fecha_entrada, 'fecha_salida' => $model->fecha_salida]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Reservas model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $habitaciones_id
     * @param string $fecha_entrada
     * @param string $fecha_salida
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($habitaciones_id, $fecha_entrada, $fecha_salida)
    {
        $this->findModel($habitaciones_id, $fecha_entrada, $fecha_salida)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Reservas model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $habitaciones_id
     * @param string $fecha_entrada
     * @param string $fecha_salida
     * @return Reservas the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($habitaciones_id, $fecha_entrada, $fecha_salida)
    {
        if (($model = Reservas::findOne(['habitaciones_id' => $habitaciones_id, 'fecha_entrada' => $fecha_entrada, 'fecha_salida' => $fecha_salida])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/reservas/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Reservas */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="reservas-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'habitaciones_id')->textInput() ?>

    <?= $form->field($model, 'clientes_id')->textInput() ?>

    <?= $form->field($model, 'fecha_entrada')->textInput() ?>

    <?= $form->field($model, 'fecha_salida')->textInput() ?>

    <?= $form->field($model, 'precio')->textInput() ?>

    <?= $form->field($model, 'observacion')->textarea(['rows' => 6]) ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/reservas/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ReservasSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="reservas-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'habitaciones') ?>

    <?= $form->field($model, 'clientes') ?>

    <?= $form->field($model, 'precio') ?>

    <?= $form->field($model, 'fecha_entrada') ?>

    <?= $form->field($model, 'fecha_salida') ?>

    <?= $form->field($model, 'dias') ?>

    <?= $form->field($model, 'observacion') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/reservas/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Reservas */

$this->title = 'Create Reservas';
$this->params['breadcrumbs'][] = ['label' => 'Reservas', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="reservas-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/reservas/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\ReservasSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Reservas';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="reservas-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Nueva Reserva', ['create'], ['class' => 'btn 
        btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            [
                'attribute' => 'id',
                'format' => 'raw',
                'value' => function($model) {
                    return Html::a($model->id, ['reservas/view', 'id' => $model->id]);
                },
                'contentOptions' => [
                    'class' => 'text-center',
                    'style'=> 'width: 10px; color: #f00; font-size: 1.2em;',
                ],
            ],
            [
                'label' => 'Nº Hab.',
                'format' => 'raw',
                'value' => function ($data) {
                $habitacion = \app\models\Habitaciones::findOne($data->habitaciones_id);

                return Html::a($habitacion->numero, ['habitaciones/view', 'id' => $habitacion->id]);
                },
                'contentOptions' => [
                    'class' => 'text-center',
                    'style'=> 'width: 10px; color: #f00; font-size: 1.2em;',
                ],
            ],
            [
                'label' => 'Cliente',
                'format' => 'raw',
                'value' => function ($data) {
                    $usuario = \app\models\Clientes::findOne
                    ($data->clientes_id);

                    return Html::a($usuario->nombre, ['clientes/view', 'id' => $usuario->id]);
                },
                'contentOptions' => [
                    'class' => 'text-center',
                    'style'=> 'width: 10px; font-size: 1.2em;',
                ],
            ],
            [
                'attribute' => 'precio',
                'format' => ['currency'],
                'contentOptions' => [
                    'class' => 'text-center',
                    'style'=> 'width: 10px; font-size: 1.1em;',
                ],
            ],
            [
                'attribute' => 'fecha_entrada',
                'format' => ['date'],
                'contentOptions' => [
                    'class' => 'text-center',
                    'style'=> 'width: 10px; font-size: 1.1em;',
                ],
            ],
            [
                'attribute' => 'fecha_salida',
                'format' => ['date'],
                'contentOptions' => [
                    'class' => 'text-center',
                    'style'=> 'width: 10px; font-size: 1.1em;',
                ],
            ],
            [
                'attribute' => 'dias',
                'contentOptions' => [
                    'class' => 'text-center',
                    'style'=> 'width: 10px; color: #f00; font-size: 1.2em;',
                ],
            ],
            'observacion',
        ],
    ]); ?>
</div>

views/reservas/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Reservas */

$this->title = 'Actualizar Reservaa '.$model->id;
$this->params['breadcrumbs'][] = ['label' => 'Reservas', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->habitaciones_id, 'url' => ['view', 'habitaciones_id' => $model->habitaciones_id, 'fecha_entrada' => $model->fecha_entrada, 'fecha_salida' => $model->fecha_salida]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="reservas-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/reservas/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Reservas */

$this->title = $model->habitaciones_id;
$this->params['breadcrumbs'][] = ['label' => 'Reservas', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="reservas-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'habitaciones_id' => $model->habitaciones_id, 'fecha_entrada' => $model->fecha_entrada, 'fecha_salida' => $model->fecha_salida], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'habitaciones_id' => $model->habitaciones_id, 'fecha_entrada' => $model->fecha_entrada, 'fecha_salida' => $model->fecha_salida], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'habitaciones_id',
            'fecha_entrada',
            'fecha_salida',
            'clientes_id',
            'precio',
            'observacion:ntext',
        ],
    ]) ?>

</div>